import { Page, Locator } from '@playwright/test';

/**
 * ISE1551Page
 * Auto-generated by Layer 4 (Playwright Automation Engineer).
 *
 * Selectors below are REUSED VERBATIM from AbsenceCreationPage.ts, surfaced by the
 * Layer 3 vector store, so DOM bindings stay consistent across the suite.
 * Review and rename generated action methods to match the feature vocabulary.
 */
export class ISE1551Page {
  readonly page: Page;
  private readonly timeout = 10000;
  readonly teacherSelect: Locator;
  readonly leaveReasonSelect: Locator;
  readonly absenceDateInput: Locator;
  readonly submitAbsenceBtn: Locator;
  readonly confirmationNumber: Locator;
  readonly errorMessage: Locator;

  constructor(page: Page) {
    this.page = page;
    this.teacherSelect = page.locator('select[data-testid="teacher-select"]');
    this.leaveReasonSelect = page.locator('select[data-testid="leave-reason-select"]');
    this.absenceDateInput = page.locator('input[data-testid="absence-date-input"]');
    this.submitAbsenceBtn = page.locator('button[data-testid="submit-absence-btn"]');
    this.confirmationNumber = page.locator('div[data-testid="confirmation-number"]');
    this.errorMessage = page.locator('div[data-testid="error-message"]');
  }

  async navigateTo(path: string = '/'): Promise<void> {
    await this.page.goto(path);
    await this.page.waitForLoadState('networkidle');
  }

  async selectTeacher(value: string): Promise<void> {
    await this.teacherSelect.waitFor({ state: 'visible', timeout: this.timeout });
    await this.teacherSelect.selectOption({ label: value });
  }

  async selectLeaveReason(value: string): Promise<void> {
    await this.leaveReasonSelect.waitFor({ state: 'visible', timeout: this.timeout });
    await this.leaveReasonSelect.selectOption({ label: value });
  }

  async fillAbsenceDate(value: string): Promise<void> {
    await this.absenceDateInput.waitFor({ state: 'visible', timeout: this.timeout });
    await this.absenceDateInput.fill(value);
  }

  async clickSubmitAbsence(): Promise<void> {
    await this.submitAbsenceBtn.click();
  }

  async getConfirmationNumberText(): Promise<string | null> {
    await this.confirmationNumber.waitFor({ state: 'visible', timeout: this.timeout });
    return this.confirmationNumber.textContent();
  }

  async isConfirmationNumberVisible(): Promise<boolean> {
    return this.confirmationNumber.isVisible();
  }

  async getErrorMessageText(): Promise<string | null> {
    await this.errorMessage.waitFor({ state: 'visible', timeout: this.timeout });
    return this.errorMessage.textContent();
  }

  async isErrorMessageVisible(): Promise<boolean> {
    return this.errorMessage.isVisible();
  }
}
